### ISSUE TITLE
yfcc_row_id 0 indexed or 1 indexed

### ISSUE THREAD

**Issue by ramprs** [abhimanyudubey/GeoYFCC#1]
Hi, 

Thank you for making the dataset public. I assume yfcc_row_id is the line number in the yfcc100m_dataset file. May I know if `yfcc_row_id` is 0 indexed or 1 indexed?

Thanks

**Comment by abhimanyudubey** [comment]
The `yfcc_row_id` corresponds to the first column in the `yfcc100m_dataset` metadata file within the YFCC dataset. This index begins from `0`.
